--- 
- name: i want to deploy java application
  get_url:
    url: https://raju12456.s3.ap-south-1.amazonaws.com/Downloads+10_28_2021+3_02_53+PM.png
    dest: /opt/tomcat/webapps/mahalogin.war
    force_basic_auth: yes

- name: i want to deploy jenkins as java application
  get_url:
    url: https://get.jenkins.io/war-stable/2.319.1/jenkins.war
    dest: /opt/tomcat/webapps/jenkins.war
    force_basic_auth: yes